### ISSUE TITLE
Метод mostPlayerByGenre  в классе Player выдает ответ null вместо названия игры, в которую больше всего играли в выбраном жанре, если игры одного жанра.

### ISSUE THREAD

**Issue by Andrej-ori** [Andrej-ori/TeamWork#10]
# Описание:

Тест метода mostPlayerByGenre (должен определять игру заданного жанра, в которую играли больше всего) падает
(подготовка теста: установлено 2 игры заданного жанра, добавлено количество часов, проигранное в каждую из 2х игр).

# Локация дефекта:

https://github.com/Andrej-ori/TeamWork/blob/0027d72da351de6f55792096d9a86251c8e63e76/src/main/java/ru/netology/Player.java#L57-L62

# Шаги воспроизведения:

Открыть [код программы](https://github.com/Andrej-ori/TeamWork) в IDEA

Запустить тест  [shouldReturnMostPlayedByGenre](https://github.com/Andrej-ori/TeamWork/blob/0027d72da351de6f55792096d9a86251c8e63e76/src/test/java/ru/netology/PlayerTest.java#L116-L138) класса PlayerTest

**Ожидаемый результат:** Тест shouldReturnMostPlayedByGenre проходит успешно. В логе отсутствуют ошибки
**Фактический результат:** ТестshouldReturnMostPlayedByGenre падает с ошибкой: 
org.opentest4j.AssertionFailedError: 
Expected :Арканоид
Actual   :null

# Скриншот:

![Screenshot_3](https://user-images.githubusercontent.com/107578974/188925738-aacc3c66-bcce-413c-96d5-7db61b556f89.jpg)

# Окружение:
* **Операционная система:** Windows 10 Pro 21H1
* **IDE:** IntelliJ IDEA 2022.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Vinarskaya** [comment]
Прошу поменять Ожидаемый результат на: Game expected = game2;

Метод mostPlayerByGenre принимает жанр и возвращает игру (не название) этого жанра, в которую играли больше всего.

**Comment by Andrej-ori** [comment]
ок. внесены изменения в тест
