### ISSUE TITLE
Метод mostPlayerByGenre в классе Player выдает ответ null вместо названия игры, в которую больше всего играли в выбраном жанре, если игры разных жанров.

### ISSUE THREAD

**Issue by Andrej-ori** [Andrej-ori/TeamWork#13]
# Описание:

Тест метода mostPlayerByGenre (должен определять игру заданного жанра, в которую играли больше всего) падает
(подготовка теста: установлено 2 игры заданного жанра, и игра другого жанра,  добавлено количество часов, проигранное в каждую из 3х игр).

# Локация дефекта:

https://github.com/Andrej-ori/TeamWork/blob/0027d72da351de6f55792096d9a86251c8e63e76/src/main/java/ru/netology/Player.java#L57-L62

# Шаги воспроизведения:

Открыть [код программы](https://github.com/Andrej-ori/TeamWork) в IDEA

Запустить тест  [shouldReturnMostPlayedByGenreWhenSomeGamesDifferentGenres](https://github.com/Andrej-ori/TeamWork/blob/0027d72da351de6f55792096d9a86251c8e63e76/src/test/java/ru/netology/PlayerTest.java#L140-L165) класса PlayerTest

**Ожидаемый результат:** Тест shouldReturnMostPlayedByGenreWhenSomeGamesDifferentGenres проходит успешно. В логе отсутствуют ошибки
**Фактический результат:** shouldReturnMostPlayedByGenreWhenSomeGamesDifferentGenres падает с ошибкой: 
org.opentest4j.AssertionFailedError: 
Expected :Покорение Марса
Actual   :null

# Скриншот:

![Screenshot_2](https://user-images.githubusercontent.com/107578974/188934779-c1908473-f309-462a-83c2-8f644e38a3f4.jpg)

# Окружение:
* **Операционная система:** Windows 10 Pro 21H1
* **IDE:** IntelliJ IDEA 2022.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Vinarskaya** [comment]
Прошу изменить Ожидаемый результат на: Game expected = game2;

Метод mostPlayerByGenre принимает жанр и возвращает игру (не название) этого жанра, в которую играли больше всего.

**Comment by Andrej-ori** [comment]
ок. внесены изменения в тест
